# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='dong',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='text',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
