# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170703_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='dong',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
