# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170705_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='dong',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
