# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
