# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='user',
        ),
        migrations.DeleteModel(
            name='bank',
        ),
    ]
