# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.BigIntegerField(default=''),
        ),
    ]
