# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_passwordresetcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcodes',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
