# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170703_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 3, 14, 8, 15, 398159)),
        ),
    ]
