# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20170706_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetcodes',
            old_name='passwordwe',
            new_name='password',
        ),
    ]
