# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20170707_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='dong',
        ),
    ]
