# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20170703_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default='2015-11-04'),
        ),
    ]
